name: Backup Firestore Data

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'
jobs:
  backup:
    runs-on: ubuntu-latest
    environment: production
    env:
      FIREBASE_API_KEY: ${{ secrets.FIREBASE_API_KEY }}
      FIREBASE_APP_ID: ${{ secrets.FIREBASE_APP_ID }}
      FIREBASE_AUTH_DOMAIN: ${{ secrets.FIREBASE_AUTH_DOMAIN }}
      FIREBASE_MESSAGING_SENDER_ID: ${{ secrets.FIREBASE_MESSAGING_SENDER_ID }}
      FIREBASE_PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}
      FIREBASE_STORAGE_BUCKET: ${{ secrets.FIREBASE_STORAGE_BUCKET }}
    steps:
    - uses: google-github-actions/setup-gcloud@v0
      with:
        service_account_key: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_CALL_LOGGER_PROD }}
        export_default_credentials: true
    - run: gcloud config set project $FIREBASE_PROJECT_ID
    - run: gcloud firestore export $FIREBASE_STORAGE_BUCKET
